#!/usr/bin/env python3
"""
CLI Runner for executing the Mark Richards Pipes & Filters Hardware Benchmarking Pipeline.
"""

from pathlib import Path
import sys

# Support both `python main.py` and `python scripts/run_pipeline.py`.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.hardware_benchmarking.config import load_settings
from src.hardware_benchmarking.application.pipeline_factory import build_pipeline


def export_report_index(cpu_report: str, gpu_report: str) -> Path:
    """Create a small landing page pointing evaluators at the latest run reports."""
    index_path = Path("outputs/reports/latest.md")
    index_path.parent.mkdir(parents=True, exist_ok=True)
    cpu_link = Path(cpu_report).resolve().relative_to(index_path.parent.resolve())
    gpu_link = Path(gpu_report).resolve().relative_to(index_path.parent.resolve())
    index_path.write_text(
        "# Latest hardware benchmarking reports\n\n"
        "These reports are generated by the completed Pipes & Filters pipeline. "
        "Each linked folder contains its own graphics in `assets/`.\n\n"
        f"- [CPU model report]({cpu_link.as_posix()})\n"
        f"- [GPU model report]({gpu_link.as_posix()})\n",
        encoding="utf-8",
    )
    return index_path


def run():
    print("=" * 75)
    print("PIPES & FILTERS ARCHITECTURE — MLOPS HARDWARE PIPELINE")
    print("=" * 75)

    settings = load_settings()
    cpu_chain, cpu_ctx = build_pipeline(settings, settings.domains["cpu"])
    cpu_res = cpu_chain.execute(cpu_ctx)
    gpu_chain, gpu_ctx = build_pipeline(settings, settings.domains["gpu"])
    gpu_res = gpu_chain.execute(gpu_ctx)
    report_index = export_report_index(cpu_res.report_path, gpu_res.report_path)

    print("\n" + "=" * 75)
    print("PIPELINE EXECUTION COMPLETE:")
    print(f"  - Intel CPU Champion Model: {cpu_res.champion_model_name} (Test R²: {cpu_res.champion_metrics['R2_Score']:.4f})")
    print(f"  - All GPU Champion Model:   {gpu_res.champion_model_name} (Test R²: {gpu_res.champion_metrics['R2_Score']:.4f})")
    print(f"  - CPU reader report: {cpu_res.report_path}")
    print(f"  - GPU reader report: {gpu_res.report_path}")
    print(f"  - Latest report index: {report_index}")
    print("=" * 75)


if __name__ == "__main__":
    run()
